### ISSUE TITLE
general ui improvements

### ISSUE THREAD

**Issue by ryankurte** [mobilecoinofficial/ledger-mob#18]
feedback from user testing

- [x] add nav indicators to home page
- [x] clarify language for `accept|approve`, `deny|reject` prompts
- [x] swap accept / reject ordering (accept should come first)
- [x] reorder transaction summaries (changes, fee, balance)
  (including refactor of report generation to avoid squashing self transactions)
  https://github.com/mobilecoinfoundation/mobilecoin/pull/3316
- [x] display standard b58 addresses for local account / in transaction summaries (#20)

**Comment by holtzman** [comment]
@ryankurte I think that accept should come before reject. That is the pattern of all of the Ledger Apps I've used so far, and it also adheres to a UX principle of having the "golden path" be the least work.

Currently the MobileCoin app is the reverse.
