### ISSUE TITLE
internal security review

### ISSUE THREAD

**Issue by ryankurte** [mobilecoinofficial/ledger-mob#3]
we're now close enough to feature complete that it's reasonable to start an internal code / security review! following from `0.8.0` changes should be substantially smaller and will managed through the standard pr / review process.

`vendor/` directories should be considered out-of-scope as these (have|do|will) undergo the standard internal review process, and we're working to merge back changes until the vendored versions match upstream / are no longer required.

tasks / improvements (an incomplete list):

- [x] add lockfiles
- [x] add `fmt`, `clippy`
- [ ] add APDU fuzzing
- [x] add `miri` tests (_if_ we can get these running over `core`)
- [x] add security / reporting policy
- [x] resolve [dependabot](https://github.com/mobilecoinofficial/ledger-mob/security/dependabot) warnings

**Comment by ryankurte** [comment]
huh, yeah they're on the internal one / have updated lockfiles since:
- https://github.com/mobilecoinofficial/ledger-mob/security/advisories
- https://github.com/mobilecoinofficial/ledger-mob/security/dependabot

**Comment by isis-mc** [comment]
#10 i think should fix the 5th checkbox?
